### PR TITLE
Lab6Final

### PR DESCRIPTION
**Pull request by cmerrill11**
@CameronPeloquin Ready for PR

### CODE REVIEW

**Comment by CameronPeloquin** [comment]
For Problem 2, you have a typo. You say inlikely instead of Unlikely, Also for your math equations there must be a typo, as it is showing the code rather than the symbols.

**Comment by CameronPeloquin** [comment]
In the paragraph below the plot comparing the two histograms, you have another typo, where you say nnear instead of near.

**Comment by CameronPeloquin** [comment]
For problem 2, maybe go a little more in depth about how the histogram shows why it is unlikely for the value to be the true signal, when talking about if the distribution is biased.

**Comment by CameronPeloquin** [comment]
Other than that, I think it great! Awesome job.

**Comment by cmerrill11** [comment]
@AlexSchuy Lab 6 Final

**Pull request merged**
