### PR TITLE
Lab4

### PR DESCRIPTION
**Pull request by cmerrill11**
@CameronPeloquin Lab 4 ready for PR!

### CODE REVIEW

**Comment by CameronPeloquin** [comment]
If possible, I'd change the name to lab 3 to avoid confusion

**Comment by CameronPeloquin** [comment]
For problem 1, I would label the axis' and give the plot a title

**Comment by CameronPeloquin** [comment]
Other than that, I think the lab looks good!

**Comment by cmerrill11** [comment]
@AlexSchuy Incorrect Branch name. Adding you for PR credit

**Comment by cmerrill11** [comment]
@CameronPeloquin Lab 4 ready for PR!

**Pull request merged**
