### PR TITLE
 Lab 2

### PR DESCRIPTION
**Pull request by cmerrill11**
@CameronPeloquin Please Leave some Comments!

### CODE REVIEW

**Comment by CameronPeloquin** [comment]
For problem 4.C I would show the calculations you did to get that the signal must increase by 30%

**Comment by CameronPeloquin** [comment]
Also for problem 4.C, I would label axis' on the plot you have, and give it a title.

**Comment by CameronPeloquin** [comment]
For problem 4.D, similar to 4.C, I would show the calculations you did to get the 30% increase in signal required to be a 5 sigma event.

**Comment by CameronPeloquin** [comment]
Other than that, I think your report looks good!

**Comment by cmerrill11** [comment]
@AlexSchuy  Turning in Lab 2

**Pull request merged**
