### PR TITLE
Lab1

### PR DESCRIPTION
**Pull request by cmerrill11**
Hi @CameronPeloquin 

Please take a look at my lab and leave me some comments about things I did wrong or you want to discuss. 

I especially would appreciate discussing with you the answers to 4.D and 4.E. 

Thanks!

### CODE REVIEW

**Comment by CameronPeloquin** [comment]
For Section 1 B and C, for the writing section, I would explain what the cdf, and ppf are doing in terms of math (Calculating an Integral, and from where to where). I would also specify the type of Z table, as there are different kinds.

**Comment by CameronPeloquin** [comment]
For Section 2, I would add explanations for each of your plots, to explain the purpose of each of them, which I think is suggested in the lab assignment.

**Comment by CameronPeloquin** [comment]
I think that your Section 3 looks good, only thing I would suggest is explaining what degrees of freedom are in part A

**Comment by CameronPeloquin** [comment]
I think that your Section 4 is really good, The plots you made show how different values affect the probabilities and sigmas very well

**Comment by CameronPeloquin** [comment]
For the non continuous distributions, I think that your code and plots all look good. I would only add a title to the plot

**Comment by CameronPeloquin** [comment]
For Sections D, I think your response is good, and is what they are looking for. For section E I think it would be good to mention how the probabilities and sigmas are tied to discrete events, while the parameters are found using formulas on the data, which can output continuous values.

**Comment by cmerrill11** [comment]
@AlexSchuy turning in Lab 1

**Pull request merged**
